name: Build for QNX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /home/runner/.docker
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build
      run: |
          docker pull navsyslab/qnx:v1.1
          container_id=$(docker create navsyslab/qnx:v1.1)
          sudo docker cp $container_id:/opt/qnx650 /opt/qnx650
          sudo docker cp $container_id:/etc/qnx /etc/qnx
          sudo chown -R $USER:$USER /etc/qnx
          export \
              QNX_HOST=/opt/qnx650/host/linux/x86 \
              QNX_TARGET=/opt/qnx650/target/qnx6
          export \
              MAKEFLAGS=-I$QNX_TARGET/usr/include \
              PATH=$PATH:$QNX_HOST/usr/bin:/etc/qnx/bin
          
          ls -la build_qnx
          cd build_qnx
          make clean && make -B
          ls -la
