name: QNX CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vsomeip repository
        uses: actions/checkout@v4
        with:
          path: vsomeip

      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/build-files
          path: build-files
          cache: true

      - name: Checkout boost
        uses: actions/checkout@v4
        with:
          repository: boostorg/boost
          path: boost
          ref: boost-1.78.0
          submodules: recursive
          cache: true
  
      - name: Checkout googletest
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/googletest
          path: googletest
          ref: qnx_v1.13.0
          cache: true

      - name: Build docker
        run: |
          cd build-files/docker
          ./build-files/docker-build-qnx-image.sh

      - name: Build vsomeip
        uses: addnab/docker-run-action@v3
        with:
          image: qnx800:latest
          options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
          shell: bash
          run: |
            source ~/qnx/800/qnxsdp-env.sh
            cd ~/workspace
            WORKSPACE=$PWD
            export GTEST_ROOT=/home/runner/workspace/googletest
            cd $WORKSPACE/boost/libs/interprocess && git apply $WORKSPACE/build-files/ports/boost/interprocess_1.78.0_qnx_7.1.patch
            cd $WORKSPACE/boost/tools/build && git apply $WORKSPACE/build-files/ports/boost/tools_qnx.patch
            cd $WORKSPACE
            BOOST_CPP_VERSION_FLAG="-std=c++17" QNX_PROJECT_ROOT="$(pwd)/boost" make -C build-files/ports/boost install -j$(nproc)
            GTEST_ROOT=$GTEST_ROOT QNX_PROJECT_ROOT="$(pwd)/vsomeip" make -C build-files/ports/vsomeip install -j$(nproc)
